baseURL = "https://serramatutu.io/"
languageCode = "en-us"
theme = "dark-orange"
enableEmoji = true

title = "serramatutu"

[params]
smallSummaryThreshold = 300

# Allow raw HTML
[markup]
  [markup.highlight]
    style = "github-dark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
